services:
  - type: web
    name: smart-traffic-forecast
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: ENV
        value: production
    plan: free
